/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto

import javax.swing.JOptionPane
import modelo.Usuarios

/**
 *
 * @author Hp
 */
class JfMenuPrincipal : javax.swing.JFrame() {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var btnAcceder: javax.swing.JButton? = null
    private var butInformacion: javax.swing.JButton? = null
    private var jPanel1: javax.swing.JPanel? = null
    private var labContraseña: javax.swing.JLabel? = null
    private var labElecciones2019: javax.swing.JLabel? = null
    private var labFondoSistema: javax.swing.JLabel? = null
    private var labLogoEspe: javax.swing.JLabel? = null
    private var labSistemadevotoelectronico: javax.swing.JLabel? = null
    private var labUsuario: javax.swing.JLabel? = null
    private var txtContraseña: javax.swing.JTextField? = null
    private var txtUsuario: javax.swing.JTextField? = null

    init {
        initComponents()
        this.setLocationRelativeTo(null)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    fun initComponents() {

        butInformacion = javax.swing.JButton()
        labSistemadevotoelectronico = javax.swing.JLabel()
        labElecciones2019 = javax.swing.JLabel()
        labUsuario = javax.swing.JLabel()
        txtUsuario = javax.swing.JTextField()
        labContraseña = javax.swing.JLabel()
        txtContraseña = javax.swing.JTextField()
        labLogoEspe = javax.swing.JLabel()
        btnAcceder = javax.swing.JButton()
        jPanel1 = javax.swing.JPanel()
        labFondoSistema = javax.swing.JLabel()

        defaultCloseOperation = javax.swing.WindowConstants.EXIT_ON_CLOSE
        minimumSize = java.awt.Dimension(648, 520)
        isResizable = false
        contentPane.layout = null

        butInformacion!!.font = java.awt.Font("Times New Roman", 1, 14) // NOI18N
        butInformacion!!.text = "INFORMACIÓN "
        butInformacion!!.addActionListener { evt -> butInformacionActionPerformed(evt) }
        contentPane.add(butInformacion)
        butInformacion!!.setBounds(29, 434, 145, 50)

        labSistemadevotoelectronico!!.font = java.awt.Font("Times New Roman", 1, 23) // NOI18N
        labSistemadevotoelectronico!!.text = "SISTEMA DE VOTO ELECTRÓNICO "
        contentPane.add(labSistemadevotoelectronico)
        labSistemadevotoelectronico!!.setBounds(110, 30, 440, 28)

        labElecciones2019!!.font = java.awt.Font("Times New Roman", 1, 24) // NOI18N
        labElecciones2019!!.text = "ELECCIONES 2019"
        contentPane.add(labElecciones2019)
        labElecciones2019!!.setBounds(220, 80, 210, 28)

        labUsuario!!.font = java.awt.Font("Times New Roman", 1, 18) // NOI18N
        labUsuario!!.text = "Usuario"
        contentPane.add(labUsuario)
        labUsuario!!.setBounds(210, 210, 61, 22)
        contentPane.add(txtUsuario)
        txtUsuario!!.setBounds(210, 250, 236, 32)

        labContraseña!!.font = java.awt.Font("Times New Roman", 1, 18) // NOI18N
        labContraseña!!.text = "Contraseña"
        contentPane.add(labContraseña)
        labContraseña!!.setBounds(210, 300, 89, 22)

        txtContraseña!!.addActionListener { evt -> txtContraseñaActionPerformed(evt) }
        contentPane.add(txtContraseña)
        txtContraseña!!.setBounds(210, 330, 236, 34)

        labLogoEspe!!.icon = javax.swing.ImageIcon(javaClass.getResource("/Logos/Logo_ESPE.png")) // NOI18N
        labLogoEspe!!.text = "jLabel5"
        contentPane.add(labLogoEspe)
        labLogoEspe!!.setBounds(0, 0, 120, 110)

        btnAcceder!!.font = java.awt.Font("Times New Roman", 1, 14) // NOI18N
        btnAcceder!!.text = "ACCEDER"
        btnAcceder!!.addActionListener { evt -> btnAccederActionPerformed(evt) }
        contentPane.add(btnAcceder)
        btnAcceder!!.setBounds(440, 430, 170, 50)

        labFondoSistema!!.icon = javax.swing.ImageIcon(javaClass.getResource("/Logos/FondoSistema.jpg")) // NOI18N
        jPanel1!!.add(labFondoSistema)

        contentPane.add(jPanel1)
        jPanel1!!.setBounds(0, 0, 650, 500)

        pack()
    }// </editor-fold>//GEN-END:initComponents

    private fun butInformacionActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_butInformacionActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Bienvenido al sistema de votación etc etc...\n" + "Recuerde para ingresar al sistema su usuario y contrañesa son su número de ID o cédula")

    }//GEN-LAST:event_butInformacionActionPerformed

    private fun txtContraseñaActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private fun btnAccederActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_btnAccederActionPerformed
        // TODO add your handling code here:
        val modSql = SqlUsuarios()
        val mod = Usuarios()

        val pass = String(txtContraseña!!.text)

        if (txtUsuario!!.text != "" && pass != "") {
            mod.usuario = txtUsuario!!.text
            mod.password = pass

            if (modSql.loginAdmin(mod)) {

                this.dispose()

                if (frmAdmin == null) {
                    frmAdmin = JfAdministrador()
                    frmAdmin!!.isVisible = true
                }

            } else if (modSql.loginVotante(mod)) {
                this.dispose()

                if (frmVotante == null) {
                    frmVotante = JfVotante()
                    frmVotante!!.isVisible = true
                }
            } else {
                JOptionPane.showMessageDialog(null, "Datos incorrectos")
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe ingresar sus datos")
        }

    }//GEN-LAST:event_btnAccederActionPerformed

    companion object {

        var frmAdmin: JfAdministrador? = null
        var frmVotante: JfVotante? = null

        /**
         * @param args the command line arguments
         */
        @JvmStatic
        fun main(args: Array<String>) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
            try {
                for (info in javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus" == info.name) {
                        javax.swing.UIManager.setLookAndFeel(info.className)
                        break
                    }
                }
            } catch (ex: ClassNotFoundException) {
                java.util.logging.Logger.getLogger(JfMenuPrincipal::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: InstantiationException) {
                java.util.logging.Logger.getLogger(JfMenuPrincipal::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: IllegalAccessException) {
                java.util.logging.Logger.getLogger(JfMenuPrincipal::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: javax.swing.UnsupportedLookAndFeelException) {
                java.util.logging.Logger.getLogger(JfMenuPrincipal::class.java!!.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            }

            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater { JfMenuPrincipal().isVisible = true }
        }
    }
    // End of variables declaration//GEN-END:variables
}
