/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto

import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.awt.event.MouseListener
import java.util.StringTokenizer
import javax.swing.JOptionPane
import modelo.Candidato
import modelo.SqlCandidato
import modelo.SqlVotos
import modelo.Votante
import modelo.Votos

/**
 *
 * @author Hp
 */
class JfVotante : javax.swing.JFrame(), MouseListener {

    /**
     * Creates new form JfVotante
     */
    internal var votos = Votos()
    internal var cand = Candidato()

    internal var candidato = SqlCandidato()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var butBlanco: javax.swing.JButton? = null
    private var butSalir: javax.swing.JButton? = null
    private var butVotar: javax.swing.JButton? = null
    private var jPanel1: javax.swing.JPanel? = null
    private var labCandidatoA: javax.swing.JLabel? = null
    private var labCandidatoB: javax.swing.JLabel? = null
    private var labCandidatoC: javax.swing.JLabel? = null
    private var labCandidatos: javax.swing.JLabel? = null
    private var labFondoSistema: javax.swing.JLabel? = null
    private var labFotoCanA: javax.swing.JLabel? = null
    private var labFotoCanB: javax.swing.JLabel? = null
    private var labFotoCanC: javax.swing.JLabel? = null

    init {
        initComponents()
        this.setLocationRelativeTo(null)

        labFotoCanA!!.addMouseListener(object : MouseAdapter() {
            @Override
            fun mousePressed(e: MouseEvent) {
                val token = StringTokenizer(labCandidatoA!!.getText())
                while (token.hasMoreTokens()) {
                    cand.nombre = token.nextToken()
                    cand.apellido = token.nextToken()
                }
                candidato.buscarPorNombreApellido(cand)
                System.out.println("id del candidato: " + cand.identificacion)
            }
        })

        labFotoCanB!!.addMouseListener(object : MouseAdapter() {
            @Override
            fun mousePressed(e: MouseEvent) {
                val token = StringTokenizer(labCandidatoB!!.getText())
                while (token.hasMoreTokens()) {
                    cand.nombre = token.nextToken()
                    cand.apellido = token.nextToken()
                }
                candidato.buscarPorNombreApellido(cand)
                System.out.println("id del candidato: " + cand.identificacion)
            }
        })

        labFotoCanC!!.addMouseListener(object : MouseAdapter() {
            @Override
            fun mousePressed(e: MouseEvent) {
                val token = StringTokenizer(labCandidatoC!!.getText())
                while (token.hasMoreTokens()) {
                    cand.nombre = token.nextToken()
                    cand.apellido = token.nextToken()
                }
                candidato.buscarPorNombreApellido(cand)
                System.out.println("id del candidato: " + cand.identificacion)
            }
        })
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    fun initComponents() {

        labCandidatos = javax.swing.JLabel()
        labCandidatoB = javax.swing.JLabel()
        labCandidatoC = javax.swing.JLabel()
        butVotar = javax.swing.JButton()
        butBlanco = javax.swing.JButton()
        butSalir = javax.swing.JButton()
        jPanel1 = javax.swing.JPanel()
        labCandidatoA = javax.swing.JLabel()
        labFotoCanA = javax.swing.JLabel()
        labFotoCanB = javax.swing.JLabel()
        labFotoCanC = javax.swing.JLabel()
        labFondoSistema = javax.swing.JLabel()

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE)
        setMinimumSize(java.awt.Dimension(650, 510))
        getContentPane().setLayout(null)

        labCandidatos!!.setFont(java.awt.Font("Times New Roman", 1, 36)) // NOI18N
        labCandidatos!!.setText("CANDIDATOS ")
        getContentPane().add(labCandidatos)
        labCandidatos!!.setBounds(222, 22, 249, 42)

        labCandidatoB!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCandidatoB!!.setText("Alberto Plaza")
        getContentPane().add(labCandidatoB)
        labCandidatoB!!.setBounds(250, 130, 106, 22)

        labCandidatoC!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCandidatoC!!.setText("Carla Salas")
        getContentPane().add(labCandidatoC)
        labCandidatoC!!.setBounds(450, 130, 88, 22)

        butVotar!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        butVotar!!.setText("VOTAR")
        butVotar!!.addActionListener(object : java.awt.event.ActionListener() {
            fun actionPerformed(evt: java.awt.event.ActionEvent) {
                butVotarActionPerformed(evt)
            }
        })
        getContentPane().add(butVotar)
        butVotar!!.setBounds(20, 430, 94, 38)

        butBlanco!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        butBlanco!!.setText("EN BLANCO")
        butBlanco!!.addActionListener(object : java.awt.event.ActionListener() {
            fun actionPerformed(evt: java.awt.event.ActionEvent) {
                butBlancoActionPerformed(evt)
            }
        })
        getContentPane().add(butBlanco)
        butBlanco!!.setBounds(240, 430, 136, 38)

        butSalir!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        butSalir!!.setText("SALIR")
        butSalir!!.addActionListener(object : java.awt.event.ActionListener() {
            fun actionPerformed(evt: java.awt.event.ActionEvent) {
                butSalirActionPerformed(evt)
            }
        })
        getContentPane().add(butSalir)
        butSalir!!.setBounds(480, 430, 85, 38)

        jPanel1!!.setLayout(org.netbeans.lib.awtextra.AbsoluteLayout())

        labCandidatoA!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCandidatoA!!.setText("Veronica Zambrano")
        jPanel1!!.add(labCandidatoA, org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1))

        labFotoCanA!!.setIcon(javax.swing.ImageIcon(getClass().getResource("/Logos/foto-carnet-chica.png"))) // NOI18N
        jPanel1!!.add(labFotoCanA, org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 135, 180))

        labFotoCanB!!.setIcon(javax.swing.ImageIcon(getClass().getResource("/Logos/foto-canet.png"))) // NOI18N
        jPanel1!!.add(labFotoCanB, org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 135, 180))

        labFotoCanC!!.setIcon(javax.swing.ImageIcon(getClass().getResource("/Logos/foto-carnet-chica3.png"))) // NOI18N
        jPanel1!!.add(labFotoCanC, org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 130, 180))

        labFondoSistema!!.setIcon(javax.swing.ImageIcon(getClass().getResource("/Logos/FondoSistema.jpg"))) // NOI18N
        jPanel1!!.add(labFondoSistema, org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500))

        getContentPane().add(jPanel1)
        jPanel1!!.setBounds(0, 0, 650, 500)

        pack()
    }// </editor-fold>//GEN-END:initComponents

    private fun butSalirActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_butSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0)
    }//GEN-LAST:event_butSalirActionPerformed

    private fun butVotarActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_butVotarActionPerformed
        // TODO add your handling code here:
        val voto = SqlVotos()
        votos.idCandidato = cand.identificacion
        votos.voto = '1'
        votos.blanco = '0'
        voto.registrar(votos)
        JOptionPane.showMessageDialog(null, "Usted a votado por: " + cand.nombre + " " + cand.apellido)
        System.exit(0)
    }//GEN-LAST:event_butVotarActionPerformed

    private fun butBlancoActionPerformed(evt: java.awt.event.ActionEvent) {//GEN-FIRST:event_butBlancoActionPerformed
        // TODO add your handling code here:
        val voto = SqlVotos()
        val numero: Int
        //numero = (int) (Math.random() * 100000) + 1;
        numero = cand.identificacion
        //if(numero<200000){
        votos.idCandidato = 1002552312
        votos.voto = '0'
        votos.blanco = '1'
        voto.registrar(votos)
        JOptionPane.showMessageDialog(null, "usted a dejado su voto en blanco")
        System.exit(0)
        //}

    }//GEN-LAST:event_butBlancoActionPerformed
    // End of variables declaration//GEN-END:variables

    @Override
    fun mouseClicked(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    fun mousePressed(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    fun mouseReleased(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    fun mouseEntered(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    fun mouseExited(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    companion object {

        /**
         * @param args the command line arguments
         */
        fun main(args: Array<String>) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
            try {
                for (info in javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName())
                        break
                    }
                }
            } catch (ex: ClassNotFoundException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: InstantiationException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: IllegalAccessException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: javax.swing.UnsupportedLookAndFeelException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            }

            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(object : Runnable() {
                fun run() {
                    JfVotante().setVisible(true)
                }
            })
        }
    }
}
