/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto

import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.awt.event.MouseListener
import java.util.StringTokenizer
import javax.swing.JOptionPane
import modelo.Candidato
import modelo.Votos

/**
 *
 * @author Hp
 */
class JfVotante : javax.swing.JFrame(), MouseListener {

    /**
     * Creates new form JfVotante
     */
    internal var votos = Votos()
    internal var cand = Candidato()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var butBlanco: javax.swing.JButton? = null
    private var butSalir: javax.swing.JButton? = null
    private var butVotar: javax.swing.JButton? = null
    private var jPanel1: javax.swing.JPanel? = null
    private var labCandidatoA: javax.swing.JLabel? = null
    private var labCandidatoB: javax.swing.JLabel? = null
    private var labCandidatoC: javax.swing.JLabel? = null
    private var labCandidatos: javax.swing.JLabel? = null
    private var labFondoSistema: javax.swing.JLabel? = null
    private var labFotoCanA: javax.swing.JLabel? = null
    private var labFotoCanB: javax.swing.JLabel? = null
    private var labFotoCanC: javax.swing.JLabel? = null

    init {
        initComponents()
        this.setLocationRelativeTo(null)

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    fun initComponents() {

        labCandidatos = javax.swing.JLabel()
        labCandidatoB = javax.swing.JLabel()
        labCandidatoC = javax.swing.JLabel()
        butVotar = javax.swing.JButton()
        butBlanco = javax.swing.JButton()
        butSalir = javax.swing.JButton()
        jPanel1 = javax.swing.JPanel()
        labCandidatoA = javax.swing.JLabel()
        labFotoCanA = javax.swing.JLabel()
        labFotoCanB = javax.swing.JLabel()
        labFotoCanC = javax.swing.JLabel()
        labFondoSistema = javax.swing.JLabel()

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE)
        setMinimumSize(java.awt.Dimension(650, 510))
        getContentPane().setLayout(null)

        labCandidatos!!.setFont(java.awt.Font("Times New Roman", 1, 36)) // NOI18N
        labCandidatos!!.setText("CANDIDATOS ")
        getContentPane().add(labCandidatos)
        labCandidatos!!.setBounds(222, 22, 249, 42)

        labCandidatoB!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCandidatoB!!.setText("Alberto Plaza")
        getContentPane().add(labCandidatoB)
        labCandidatoB!!.setBounds(250, 130, 106, 22)

        labCandidatoC!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCandidatoC!!.setText("Carla Salas")
        getContentPane().add(labCandidatoC)
        labCandidatoC!!.setBounds(450, 130, 88, 22)

        butVotar!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        butVotar!!.setText("VOTAR")

        getContentPane().add(butVotar)
        butVotar!!.setBounds(20, 430, 94, 38)

        butBlanco!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        butBlanco!!.setText("EN BLANCO")

        getContentPane().add(butBlanco)
        butBlanco!!.setBounds(240, 430, 136, 38)

        butSalir!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        butSalir!!.setText("SALIR")

        getContentPane().add(butSalir)
        butSalir!!.setBounds(480, 430, 85, 38)

        jPanel1!!.setLayout(org.netbeans.lib.awtextra.AbsoluteLayout())

        labCandidatoA!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCandidatoA!!.setText("Veronica Zambrano")
        jPanel1!!.add(labCandidatoA, org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1))


        getContentPane().add(jPanel1)
        jPanel1!!.setBounds(0, 0, 650, 500)

        pack()
    }// </editor-fold>//GEN-END:initComponents




    override fun mouseClicked(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }


    override fun mousePressed(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }


    override fun mouseReleased(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }


    override fun mouseEntered(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    override fun mouseExited(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    companion object {

        /**
         * @param args the command line arguments
         */
        fun main(args: Array<String>) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
            try {
                for (info in javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName())
                        break
                    }
                }
            } catch (ex: ClassNotFoundException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: InstantiationException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: IllegalAccessException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            } catch (ex: javax.swing.UnsupportedLookAndFeelException) {
                java.util.logging.Logger.getLogger(JfVotante::class.java.getName()).log(java.util.logging.Level.SEVERE, null, ex)
            }

            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater { JfVotante().setVisible(true) }
        }
    }
}
