/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package votoelectronicoproyecto


import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.awt.event.MouseListener
import javax.swing.JOptionPane

/**
 *
 * @author Hp
 */
class PanelRegistroVotantes : javax.swing.JPanel(), MouseListener {

    /**
     * Creates new form PanelRegistroVotantes
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private var butBorrarVotante: javax.swing.JButton? = null
    private var butBuscarVotante: javax.swing.JButton? = null
    private var butInfo: javax.swing.JButton? = null
    private var butLimpiarDatosVotante: javax.swing.JButton? = null
    private var butRegistrarVotante: javax.swing.JButton? = null
    private var cboTipoId: javax.swing.JComboBox<String>? = null
    private var jLabel1: javax.swing.JLabel? = null
    private var labApellidoVotante: javax.swing.JLabel? = null
    private var labCarreraVotante: javax.swing.JLabel? = null
    private var labDatosVotante: javax.swing.JLabel? = null
    private var labIdVotante: javax.swing.JLabel? = null
    private var labNivelVotante: javax.swing.JLabel? = null
    private var labNombreVotante: javax.swing.JLabel? = null
    private var labTipoIdVotante: javax.swing.JLabel? = null
    private var txtApellidoVotante: javax.swing.JTextField? = null
    private var txtCarreraVotante: javax.swing.JTextField? = null
    private var txtIdVotante: javax.swing.JTextField? = null
    private var txtNivelVotante: javax.swing.JTextField? = null
    private var txtNombreVotante: javax.swing.JTextField? = null

    init {
        initComponents()
        butInfo!!.addMouseListener(object : MouseAdapter() {
            override fun mouseEntered(e: MouseEvent) {
                JOptionPane.showMessageDialog(null, "Por favor ingrese solo el id del votante para buscar y para eliminar")
            }

        })
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    fun initComponents() {

        labDatosVotante = javax.swing.JLabel()
        labNombreVotante = javax.swing.JLabel()
        labApellidoVotante = javax.swing.JLabel()
        labIdVotante = javax.swing.JLabel()
        labTipoIdVotante = javax.swing.JLabel()
        labNivelVotante = javax.swing.JLabel()
        txtNombreVotante = javax.swing.JTextField()
        txtApellidoVotante = javax.swing.JTextField()
        txtIdVotante = javax.swing.JTextField()
        txtNivelVotante = javax.swing.JTextField()
        butBorrarVotante = javax.swing.JButton()
        butLimpiarDatosVotante = javax.swing.JButton()
        butBuscarVotante = javax.swing.JButton()
        butRegistrarVotante = javax.swing.JButton()
        labCarreraVotante = javax.swing.JLabel()
        txtCarreraVotante = javax.swing.JTextField()
        cboTipoId = javax.swing.JComboBox()
        butInfo = javax.swing.JButton()
        jLabel1 = javax.swing.JLabel()

        setMinimumSize(java.awt.Dimension(650, 651))
        setLayout(null)

        labDatosVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labDatosVotante!!.setText("DATOS DEL VOTANTE")
        add(labDatosVotante)
        labDatosVotante!!.setBounds(170, 30, 193, 22)

        labNombreVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labNombreVotante!!.setText("Nombre:")
        add(labNombreVotante)
        labNombreVotante!!.setBounds(52, 98, 68, 22)

        labApellidoVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labApellidoVotante!!.setText("Apellido:")
        add(labApellidoVotante)
        labApellidoVotante!!.setBounds(52, 148, 71, 22)

        labIdVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labIdVotante!!.setText("Id:")
        add(labIdVotante)
        labIdVotante!!.setBounds(50, 190, 22, 22)

        labTipoIdVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labTipoIdVotante!!.setText("Tipo Id:")
        add(labTipoIdVotante)
        labTipoIdVotante!!.setBounds(50, 230, 63, 22)

        labNivelVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labNivelVotante!!.setText("Nivel:")
        add(labNivelVotante)
        labNivelVotante!!.setBounds(52, 329, 45, 22)
        add(txtNombreVotante)
        txtNombreVotante!!.setBounds(138, 101, 101, 24)
        add(txtApellidoVotante)
        txtApellidoVotante!!.setBounds(141, 151, 98, 24)
        add(txtIdVotante)
        txtIdVotante!!.setBounds(140, 190, 98, 24)
        add(txtNivelVotante)
        txtNivelVotante!!.setBounds(140, 330, 98, 30)

        butBorrarVotante!!.setFont(java.awt.Font("Times New Roman", 1, 14)) // NOI18N
        butBorrarVotante!!.setText("Borrar")
        add(butBorrarVotante)
        butBorrarVotante!!.setBounds(377, 314, 91, 33)

        butLimpiarDatosVotante!!.setFont(java.awt.Font("Times New Roman", 1, 14)) // NOI18N
        butLimpiarDatosVotante!!.setText("Limpiar")

        add(butLimpiarDatosVotante)
        butLimpiarDatosVotante!!.setBounds(380, 240, 91, 33)

        butBuscarVotante!!.setFont(java.awt.Font("Times New Roman", 1, 14)) // NOI18N
        butBuscarVotante!!.setText("Buscar")

        add(butBuscarVotante)
        butBuscarVotante!!.setBounds(380, 180, 91, 33)

        butRegistrarVotante!!.setFont(java.awt.Font("Times New Roman", 1, 14)) // NOI18N
        butRegistrarVotante!!.setText("Registrar")

        add(butRegistrarVotante)
        butRegistrarVotante!!.setBounds(377, 110, 88, 33)

        labCarreraVotante!!.setFont(java.awt.Font("Times New Roman", 1, 18)) // NOI18N
        labCarreraVotante!!.setText("Carrera:")
        add(labCarreraVotante)
        labCarreraVotante!!.setBounds(50, 280, 70, 30)
        add(txtCarreraVotante)
        txtCarreraVotante!!.setBounds(140, 280, 100, 30)

        cboTipoId!!.setModel(javax.swing.DefaultComboBoxModel(arrayOf("cedula", "pasaporte")))

        add(cboTipoId)
        cboTipoId!!.setBounds(140, 230, 100, 26)

        add(butInfo)
        butInfo!!.setBounds(450, 390, 30, 32)

        jLabel1!!.setText("jLabel1")
        add(jLabel1)
        jLabel1!!.setBounds(0, 0, 500, 430)

        getAccessibleContext().setAccessibleName("")
    }// </editor-fold>//GEN-END:initComponents


    private fun limpiar() {
        txtNombreVotante!!.setText("")
        txtApellidoVotante!!.setText("")
        txtIdVotante!!.setText("")
        txtCarreraVotante!!.setText("")
        txtNivelVotante!!.setText("")
    }

    override fun mouseClicked(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    override fun mousePressed(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    override fun mouseReleased(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }

    override fun mouseEntered(e: MouseEvent) {

    }

    override fun mouseExited(e: MouseEvent) {
        throw UnsupportedOperationException("Not supported yet.") //To change body of generated methods, choose Tools | Templates.
    }


}
